# ===============================
# = Service configuration's
# ===============================
server:
  port: 8091

# ===============================
# = Security
# ===============================
access_token:
  version: 1.0
  alg: RSA256
  expiration_time: 900
  issuer: https://www.authorization-server.com
# ===============================
# = Spring
# ===============================
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:credentialdb;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

# *** To disable/enable Spring Security ***
security.ignored: /**
spring.security.enabled: false
management.security.enabled: false
security.basic.enabled: false

# ===============================
# = Logging
# ===============================
logging:
  file: ./logs/application.log
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"