# ===============================
# = Service configuration's
# ===============================
server:
  port: 8091

# ===============================
# = Access Token
# ===============================
access_token:
  alg: RSA256
  expirationTime: 900
  issuer: https://www.authorization-server.com
  keyId: a64bb46f-8a6d-4349-a537-149b07099b28
  certificate:
    password: pass
    path: certificates/sa_certificate.p12
    type: PKCS12

# ===============================
# = Cache
# ===============================
cache:
  retryDelay: 30 #seconds
  enabled: true

# ===============================
# = Spring
# ===============================
spring:
  security:
    ignored: /**
    enabled: false

  jpa:
    show-sql: true
    database: default

  datasource:
    #POSTGRESQL
    url: jdbc:postgresql://localhost:5432/backend-services
    username: postgres
    password: pass
  h2:
    #H2
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
    url: jdbc:h2:mem:backend-services;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: h2
    password: pass
    initialize: true
    driverClassName: org.h2.Driver
    schema: classpath:schema_h2.sql
    data: classpath:data_h2.sql

# *** To disable/enable Spring Security ***
management:
  security:
    enabled: false
security:
  basic:
    enabled: false

# ===============================
# = Logging
# ===============================
logging:
  file: ./logs/application.log
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"